### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by kyazdani42** [phaazon/this-week-in-neovim.org#1]
Hi @phaazon ! Very good idea :) 
I'm pretty good with writing rust code, if you need help, i'd be happy to contribute.
But it would be great to have a small contributing.md that shows the direction this will take so people can contribute to features that are needed.
Let me know if you need help !

**Comment by phaazon** [comment]
That’s a good point! I will come up with something. Indeed, I didn’t think people would want to contribute to the website directly, but more on the contents (https://github.com/phaazon/this-week-in-neovim-contents).

**Comment by kyazdani42** [comment]
I think the website is pretty simple in itself so you might not need many contributors anyway. I'll be contributing to the content, thanks :)

**Comment by phaazon** [comment]
The process has been stabilized for a while now.
